spring.application.name=ecom
spring.datasource.url=jdbc:mysql://localhost:3306/smartcart
spring.datasource.username=root
spring.datasource.password=comp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true